{-164}{-68}I always wanted to leave my country|and go somewhere else.
{-35}{23}I always wanted to come to France.
{23}{81}So, one day when I was 17, I left.
{111}{159}There I was in Paris.
{230}{329}Since I was a bit naive,
{346}{445}everyone seemed beautiful|and fabulous.
{455}{556}{Y:i}I couldn't tell cruelty from kindness.
{561}{663}{y:i}For me, people were|{y:i}the way they were.
{673}{758}{y:i}You just worked with them|{y:i}or talked with them.
{781}{861}Obviously, it was a big shock.
