FORMAT=23.98

-164 96
I always wanted to leave my country
and go somewhere else.

33 58
I always wanted to come to France.

0 58
So, one day when I was 17, I left.

30 48
There I was in Paris.

71 99
Since I was a bit naive,

17 99
everyone seemed beautiful
and fabulous.

10 101
I couldn't tell cruelty from kindness.

5 102
For me, people were
the way they were.

10 85
You just worked with them
or talked with them.

23 80
Obviously, it was a big shock.
