FORMAT=TIME

-6.84 3.99
I always wanted to leave my country
and go somewhere else.

1.38 2.42
I always wanted to come to France.

0.00 2.42
So, one day when I was 17, I left.

1.27 1.99
There I was in Paris.

2.98 4.13
Since I was a bit naive,

0.71 4.09
everyone seemed beautiful
and fabulous.

0.45 4.19
I couldn't tell cruelty from kindness.

0.21 4.27
For me, people were
the way they were.

0.40 3.56
You just worked with them
or talked with them.

0.95 3.33
Obviously, it was a big shock.
