FORMAT=TIME

59.19 4.01
I always wanted to leave my country
and go somewhere else.

1.38 2.43
I always wanted to come to France.

0.27 2.16
So, one day when I was 17, I left.

1.28 2.00
There I was in Paris.

2.99 4.15
Since I was a bit naive,

0.71 4.11
everyone seemed beautiful
and fabulous.

0.44 4.22
I couldn't tell cruelty from kindness.

0.21 4.28
For me, people were
the way they were.

0.41 3.58
You just worked with them
or talked with them.

0.94 3.35
Obviously, it was a big shock.

