#!/usr/bin/env python

# Copyright (C) 2005 Osmo Salomaa
#
# This file is part of Gaupol.
#
# Gaupol is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Gaupol is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Gaupol; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA


"""A script to test if PyEnchant has been correctly installed."""


import sys


try:
    WORD = sys.argv[1]
except IndexError:
    WORD = 'huuhaa'
    print 'No word given. Using "%s".' % WORD


# Try importing enchant.
print 'Importing enchant module:',
try:
    import enchant
    print 'success'
except ImportError, detail:
    print detail
    sys.exit()
except enchant.Error, detail:
    print detail
    sys.exit()

# List available languages.
print 'Available languages:',
try:
    langs = enchant.list_languages()
    print ', '.join(langs)
except enchant.Error, detail:
    langs = []
    print detail

# Print default language.
print 'Default language:',
try:
    print enchant.Dict().tag
except enchant.Error, detail:
    print detail

# Test all available languages.
for lang in langs:
    print '\nTesting language "%s"...' % lang
    try:
        dict = enchant.Dict(lang)
        print 'Provider:', dict.provider.name
        print 'Testing word "%s"...' % WORD
        print 'Correct:', dict.check(WORD)
        print 'Suggestions:', ', '.join(dict.suggest(WORD))
    except enchant.Error, detail:
        print detail
