.TH GAUPOL 1 "May 23, 2014"
.SH NAME
gaupol \- editor for text\-based subtitle files
.SH SYNOPSIS
.B gaupol
[\fIOPTION...\fR] [\fIFILE...\fR] [+[\fINUM\fR]]
.SH DESCRIPTION
.PP
.B gaupol
is an editor for text-based subtitle files. It supports multiple
subtitle file formats and provides means of creating subtitles, editing
texts and timing subtitles to match video.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show command line options.
.TP
\fB\-\-version\fR
Show version number.
.TP
\fB\-e\fR, \fB\-\-encoding\fR=\fIENCODING\fR
Set the character encoding to use for opening files.
.TP
\fB\-\-list\-encodings\fR
List possible character encodings to use with \fB\-\-encoding\fR.
.TP
\fB\+[NUM]\fR
Go to subtitle number NUM in the opened file. If NUM is missing go to
the last subtitle.
.TP
\fB\-t\fR, \fB\-\-translation\-file\fR=\fIFILE\fR
Open translation file.
.TP
\fB\-a\fR, \fB\-\-align\-method\fR=\fIMETHOD\fR
Method used to align translation file's subtitle texts with main
document's subtitles. Possible values are 'number' and 'position'. The
default is 'position', which compares the positions in the main document
and the translation file and inserts the translation texts so that those
positions match. Existing subtitles are skipped and new ones inserted as
needed. 'number' discards position information and inserts the N
translation texts into the first N subtitles.
.TP
\fB\-v\fR, \fB\-\-video\-file\fR=\fIFILE\fR
Load video file.
.SH AUTHOR
Written by Osmo Salomaa <otsaloma@iki.fi>.
