#!/usr/bin/env python

"""Add a ChangeLog entry."""

import os
import time

TOOL_DIR   = os.path.dirname(os.path.abspath(__file__))
SOURCE_DIR = os.path.join(TOOL_DIR, '..')

NAME  = 'Osmo Salomaa'
EMAIL = 'otsaloma@cc.hut.fi'
DATE  = time.strftime('%Y-%m-%d')

os.chdir(SOURCE_DIR)
fobj = os.popen('svn status -q')
output = fobj.read()
fobj.close()
if not output:
    raise SystemExit('No files changed.')
files = output.split('\n')
for i in reversed(range(len(files))):
    files[i] = files[i][2:].strip()
    if not files[i]:
        files.pop(i)
files.sort()

new_entry = '%s  %s  <%s>\n\n' % (DATE, NAME, EMAIL)
for path in files:
    print 'Adding %s.' % path
    new_entry += '\t* %s:\n\n' % path
fobj = file('ChangeLog', 'r')
old_entries = fobj.read()
fobj.close()
entries = new_entry + old_entries
fobj = file('ChangeLog', 'w')
fobj.write(entries)
fobj.close()
