#!/bin/sh

# Generate a GNU ChangeLog file from old ChangeLog and git logs.

SINCE=52a2a384298758ab45bdae53934c5989f050743a

cd $(dirname "$0")/..
rm -f ChangeLog
git log --pretty --numstat --summary $SINCE.. | tools/git2cl > ChangeLog
cat tools/data/ChangeLog.old >> ChangeLog
