#!/usr/bin/env python

"""
Execute Python file.

Usage: exec PATH
"""

import os
import sys

TOOL_DIR = os.path.dirname(os.path.abspath(__file__))
LIB_DIR  = os.path.join(TOOL_DIR, '..', 'lib')
sys.path.insert(0, LIB_DIR)

execfile(sys.argv[1])
