#!/usr/bin/env python

"""
Execute Python file.

USAGE: exec PATH
"""

import os
import sys

TOOL_DIR = os.path.dirname(os.path.abspath(__file__))
LIB_DIR  = os.path.join(TOOL_DIR, '..', 'lib')
os.environ['PYTHONPATH'] = LIB_DIR + ':' + os.environ['PYTHONPATH']
sys.path.insert(0, LIB_DIR)

execfile(sys.argv[1])
