#!/bin/sh

# Generate ".hidden" files in the "gaupol" directory.

cd $(dirname "$0")/.. || exit
DIRECTORIES=$(find gaupol -type d -print | grep -v .svn | sort)
for DIRECTORY in $DIRECTORIES; do
    rm -f $DIRECTORY/.hidden
    for NAME in $(ls $DIRECTORY/*.py); do
        echo $(basename ${NAME}c) >> $DIRECTORY/.hidden
    done
done
