#!/bin/bash

# Generate ".hidden" files in the "gaupol" directory.

cd $(dirname "$0")/.. || exit
DIRS=$(find gaupol -type d -print | grep -v .svn | sort)
for directory in $DIRS; do
    rm $directory/.hidden
    for name in $(ls $directory/*.py); do
        echo $(basename ${name}c) >> $directory/.hidden
    done
done
