#!/bin/sh

# List widgets with custom names in Glade XML file.
# Usage: list-glade FILE

cat "$1" \
    | grep "id=" \
    | sed "s|.*id=\"||" \
    | sed "s|\">||" \
    | grep -v "[a-z][0-9]" \
    | sort
