#!/bin/sh
# Generate pattern configuration files.
# Usage: pattern-conf PATTERN_FILE...

for PATTERN_FILE; do
    CONF_FILE=$(echo "$PATTERN_FILE" | sed "s|.in$|.conf|")
    [ "$CONF_FILE" = "$PATTERN_FILE" ] && CONF_FILE="$CONF_FILE.conf"
    echo "$CONF_FILE"
    rm -f "$CONF_FILE"
    touch "$CONF_FILE"
    echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>" >> "$CONF_FILE"
    echo "<patterns>" >> "$CONF_FILE"
    cat "$PATTERN_FILE" | grep "^_Name" \
                        | uniq \
                        | sed "s|\&|\&amp;|g" \
                        | sed "s|\"|\&quot;|g" \
                        | sed "s|^_Name=|  <pattern name=\"|" \
                        | sed "s|$|\" enabled=\"true\"/>|" \
                        >> "$CONF_FILE"

    echo "</patterns>" >> "$CONF_FILE"
done
