#!/usr/bin/env python3
"""Play video file using gaupol.VideoPlayer."""
import os, sys
directory = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(directory, ".."))
import gaupol
from gi.repository import GLib
from gi.repository import Gtk
Gtk.init()
player = gaupol.VideoPlayer()
window = Gtk.Window()
window.set_default_size(1280, 720)
loop = GLib.MainLoop()
window.connect("close-request", lambda *args: loop.quit())
window.set_child(player.widget)
window.present()
path = os.path.abspath(sys.argv[1])
player.set_path(path)
player.play()
loop.run()
