#!/usr/bin/env python3
"""Play video file using gaupol.VideoPlayer."""
import os, sys
directory = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(directory, ".."))
import gaupol
from gi.repository import Gtk
player = gaupol.VideoPlayer()
window = Gtk.Window()
window.set_default_size(1280, 720)
window.connect("delete-event", Gtk.main_quit)
window.add(player.widget)
window.show_all()
player.set_path(sys.argv[1])
player.play()
Gtk.main()
