#!/usr/bin/env python

# Profile running gaupol.main.main.
# Usage: See gaupol --help.

# Unless planning on lazy loading modules,
# we're not interested in profiling imports.
# pylint: disable=W0404,W0611
import atexit
import bisect
import chardet
import codecs
import contextlib
import copy
import cPickle
import cProfile
import enchant
import functools
import gettext
import glib
import gobject
import gst
import gtk
import gtkspell
import inspect
import itertools
import json
import linecache
import locale
import math
import optparse
import os
import pango
import platform
import pstats
import random
import re
import shutil
import string
import subprocess
import sys
import tempfile
import time
import traceback
import urllib
import urllib2
import urlparse
import webbrowser

file_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(file_dir, ".."))
os.environ["GAUPOL_DEBUG"] = ""
import aeidon
import gaupol
cProfile.run("gaupol.main.main(sys.argv[1:])", "gaupol.prof")
stats = pstats.Stats("gaupol.prof")
stats.sort_stats("cumulative")
stats.print_stats("gaupol", .2)
os.remove("gaupol.prof")
