#!/usr/bin/env python

"""Profile running gaupol.gtk.main.

Usage: See gaupol --help.
"""

import cProfile
import os
import pstats
import sys

TOOL_DIR = os.path.dirname(os.path.abspath(__file__))
LIB_DIR = os.path.join(TOOL_DIR, "..")
sys.path.insert(0, LIB_DIR)

# Unless planning on lazy loading modules,
# we're not interested in profiling imports.
# pylint: disable-msg=W0404,W0611
import atexit
import bisect
import codecs
import copy
import cPickle
import filecmp
import functools
import gc
import gettext
import glob
import gobject
import gtk
import gtk.glade
import inspect
import linecache
import locale
import os
import pango
import platform
import re
import shutil
import string
import subprocess
import sys
import tarfile
import tempfile
import textwrap
import time
import traceback
import types
import urllib
import urlparse
import webbrowser

from gaupol.gtk import main
cProfile.run("main.main(sys.argv[1:])", "gaupol.prof")
STATS = pstats.Stats("gaupol.prof")
STATS.sort_stats("cumulative")
STATS.print_stats("gaupol", .2)
os.remove("gaupol.prof")
