#!/usr/bin/env python

"""Test PyEnchant installation."""

import os
import sys

test_path = os.path.dirname(os.path.abspath(__file__))
lib_path = os.path.join(test_path, '..', 'lib')
sys.path.insert(0, lib_path)

from gaupol.base.util import langlib

print 'Importing enchant module:',
try:
    import enchant
    print 'success'
except ImportError:
    try:
        import pkg_resources
        try:
            pkg_resources.require('pyenchant')
        except pkg_resources.DistributionNotFound:
            print 'Not found'
            raise SystemExit(1)
        import enchant
        print 'success'
    except ImportError:
        print 'Not found.'
        raise SystemExit(1)
except enchant.Error, message:
    print message
    raise SystemExit(1)

print 'PyEnchant version:',
try:
    print enchant.__version__
except enchant.Error, message:
    print message

print 'Found dictionaries:'
for locale in langlib.locales:
    try:
        dictionary = enchant.Dict(locale)
        print '  * %s (using %s)' % (locale, dictionary.provider.name)
    except enchant.Error:
        pass
