#!/usr/bin/env python

"""Run svn status."""

import os

TOOL_DIR   = os.path.dirname(os.path.abspath(__file__))
SOURCE_DIR = os.path.join(TOOL_DIR, '..')

os.chdir(SOURCE_DIR)
os.system('svn status | grep -v \.pyc | sort')
