#!/usr/bin/env python

"""Run svn status."""

import os

tool_dir   = os.path.dirname(os.path.abspath(__file__))
source_dir = os.path.join(tool_dir, '..')

os.chdir(source_dir)
os.system('svn status | grep -v \.pyc | sort')
