#!/usr/bin/env python

"""
Manipulate translation files.

Needed executables in path:
* intltool-extract
* msgfmt
* msginit
* msgmerge
* xgettext
"""

import glob
import optparse
import os
import sys

tool_dir   = os.path.dirname(os.path.abspath(__file__))
source_dir = os.path.join(tool_dir, '..')

glade_dir  = os.path.join(source_dir, 'data'  , 'glade')
lib_dir    = os.path.join(source_dir, 'lib'            )
locale_dir = os.path.join(source_dir, 'locale'         )
po_dir     = os.path.join(source_dir, 'po'             )

pot_path = os.path.join(po_dir, 'gaupol.pot')
h_paths  = []
py_paths = []

def title_print(text):
    """Print a message that stands out from rest of the output."""

    print '** %s' % text

def compile_mo(lang):
    """Compile a .mo file for language lang."""

    for lang in get_languages(lang):
        title_print('Compiling .mo file for language "%s"...' % lang)
        po_path = os.path.join(po_dir, '%s.po' % lang)
        mo_dir  = os.path.join(locale_dir, lang, 'LC_MESSAGES')
        mo_path = os.path.join(mo_dir, 'gaupol.mo')
        if not os.path.isdir(mo_dir):
            os.makedirs(mo_dir)
        os.system('msgfmt -cv %s -o %s' % (po_path, mo_path))

def create_po(lang):
    """Create a .po file for a new language lang."""

    po_path = os.path.join(po_dir, '%s.po' % lang)
    if os.path.isfile(po_path):
        print '.po file for language "%s" already exists.' % lang
        raise SystemExit(1)

    title_print('Creating a .po file for language "%s"...' % lang)
    os.system('msginit -l %s -i %s -o %s' % (lang, pot_path, po_path))

def create_pot():
    """Create a .pot file."""

    title_print('Extracting strings from Glade XML files...')
    for (dirpath, dirnames, filenames) in os.walk(glade_dir):
        os.chdir(dirpath)
        for filename in filenames:
            if not filename.endswith('.glade'):
                continue
            os.system('intltool-extract --type=gettext/glade %s' % filename)
            h_paths.append(os.path.join(dirpath, '%s.h' % filename))

    for (dirpath, dirnames, filenames) in os.walk(lib_dir):
        for filename in filenames:
            if filename.endswith('.py'):
                py_paths.append(os.path.join(dirpath, filename))

    title_print('Creating a .pot file from source files...')
    paths = h_paths + py_paths
    paths = list(path.replace(source_dir, '.') for path in paths)
    os.chdir(source_dir)
    os.system('xgettext -k_ -kN_ -c -o %s %s' % (pot_path, ' '.join(paths)))

def get_languages(lang):
    """
    Get a list of languages.

    lang = xx_YY or "all"
    """
    langs = []
    if lang == 'all':
        paths = glob.glob(os.path.join(po_dir, '*.po'))
        for path in paths:
            langs.append(os.path.basename(path)[:-3])
    else:
        langs.append(lang)

    return langs

def parse_args():
    """
    Parse arguments.

    Return: options, arguments
    """
    description = \
        'Create or update translation files. LANG should be a language ' \
        'code in either format "xx" or "xx_YY". Use "all" to  process all ' \
        'languages found in the "po" directory.'
    usage = 'translate [options]'
    formatter = optparse.IndentedHelpFormatter(2, 42, None, True)
    parser = optparse.OptionParser(
        description=description,
        formatter=formatter,
        usage=usage,
    )

    parser.add_option(
        '-p',
        '--create-po',
        action='store',
        type='string',
        metavar='LANG',
        dest='create_po',
        default='',
        help='create a new .po file'
    )
    parser.add_option(
        '-u',
        '--update-po',
        action='store',
        type='string',
        metavar='LANG',
        dest='update_po',
        default='',
        help='update an existing .po file'
    )
    parser.add_option(
        '-m',
        '--compile-mo',
        action='store',
        type='string',
        metavar='LANG',
        dest='compile_mo',
        default='',
        help='compile a .mo file'
    )

    return parser.parse_args(sys.argv)

def remove_temporary_files():
    """Remove temporary files created during operations."""

    title_print('Removing temporary files...')
    for path in h_paths:
        print path.replace(source_dir, '.')
        os.remove(path)

def update_po(lang):
    """Update an existing .po file with new strings."""

    for lang in get_languages(lang):
        title_print('Updating .po file for language "%s"...' % lang)
        po_path = os.path.join(po_dir, '%s.po' % lang)
        os.system('msgmerge -U %s %s' % (po_path, pot_path))

opts, args = parse_args()

if opts.create_po:
    create_pot()
    create_po(opts.create_po)
    remove_temporary_files()
elif opts.update_po:
    create_pot()
    update_po(opts.update_po)
    remove_temporary_files()
elif opts.compile_mo:
    compile_mo(opts.compile_mo)
else:
    print 'Usage: translate [options]'
    print 'See "translate --help" for details.'
