#!/bin/sh
# Update iso-codes JSON files from /usr/share/iso-codes/json.
cd "$(dirname "$0")/.." || exit 1
cp -fv /usr/share/iso-codes/json/iso_639-2.json  data/iso-codes
cp -fv /usr/share/iso-codes/json/iso_3166-1.json data/iso-codes
cp -fv /usr/share/iso-codes/json/iso_15924.json  data/iso-codes
