#!/bin/sh
# Update iso-codes XML files from /usr/share/xml/iso-codes.

DIRNAME=$(dirname "$0")
cd "$DIRNAME/.." || exit 1

cp -uv /usr/share/xml/iso-codes/iso_639.xml   data/iso-codes
cp -uv /usr/share/xml/iso-codes/iso_3166.xml  data/iso-codes
cp -uv /usr/share/xml/iso-codes/iso_15924.xml data/iso-codes
