#!/usr/bin/env python

"""Print version numbers of dependencies."""

print 'Python:',
import sys
print '%d.%d.%d' % sys.version_info[:3]

print 'GTK:',
try:
    import gtk
    print '%d.%d.%d' % gtk.gtk_version
except ImportError:
    print 'Not found'

print 'PyGTK:',
try:
    import gtk
    print '%d.%d.%d' % gtk.pygtk_version
except ImportError:
    print 'Not found'

print 'PyEnchant:',
try:
    import enchant
    print enchant.__version__
except ImportError:
    try:
        import pkg_resources
        try:
            pkg_resources.require('pyenchant')
        except pkg_resources.DistributionNotFound:
            print 'Not found'
        else:
            import enchant
            print enchant.__version__
    except ImportError:
        print 'Not found'
except enchant.Error, message:
    print message

print 'Universal Encoding Detector:',
try:
    import chardet
    print chardet.__version__
except ImportError:
    print 'Not found.'
