#!/usr/bin/env python

"""Print version numbers of dependencies."""

# pylint: disable-msg=W0404

print "Python:",
import sys
print "%d.%d.%d" % sys.version_info[:3]

try:
    print "GTK:",
    import gtk
    print "%d.%d.%d" % gtk.gtk_version
except ImportError:
    print "N/A"

try:
    print "PyGTK:",
    import gtk
    print "%d.%d.%d" % gtk.pygtk_version
except ImportError:
    print "N/A"

try:
    import pkg_resources
    pkg_resources.require("pyenchant")
except Exception:
    pass

try:
    print "PyEnchant:",
    import enchant
    print enchant.__version__
except Exception:
    print "N/A"

try:
    print "Universal Encoding Detector:",
    import chardet
    print chardet.__version__
except ImportError:
    print "N/A"
